---
- name: Add browsers
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - firefox
    - opera
    - mailmate
    - postbox
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add desktop utility tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - cloak
    - dash
    - alfred
    - flux
    - cleanmymac
    - caffeine
    - airfoil
    - smcfancontrol
    - gpgtools
    - keybase
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add general desktop tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - libreoffice
    - balsamiq-mockups
    - airfoil
    - dropbox
    - google-drive
    - send-to-kindle
    - skype
    - transmit
    - keepassx
  when: ansible_os_family == 'Darwin'
  tags: common
